import json

from app.integrations.twenty.client import twenty_client


FIELD_DEFINITIONS = {
    "company": [
        {
            "type": "NUMBER",
            "name": "autiluxLeadScore",
            "label": "Autilux Lead Score",
            "description": "Autilux qualification score from 0 to 100",
            "icon": "IconGauge",
        },
        {
            "type": "TEXT",
            "name": "autiluxFit",
            "label": "Autilux Fit",
            "description": "Autilux qualification: LOW, MEDIUM, HIGH or HOT",
            "icon": "IconTarget",
        },
        {
            "type": "TEXT",
            "name": "autiluxResearchSummary",
            "label": "Autilux Research Summary",
            "description": "Latest company research summary generated by Autilux",
            "icon": "IconNotes",
        },
        {
            "type": "TEXT",
            "name": "autiluxSignals",
            "label": "Autilux Signals",
            "description": "Commercial signals and evidence identified by Autilux",
            "icon": "IconRadar",
        },
        {
            "type": "TEXT",
            "name": "vehicleNotes",
            "label": "Vehicle Notes",
            "description": "Fleet and vehicle information from source records",
            "icon": "IconCar",
        },
        {
            "type": "TEXT",
            "name": "companyQuality",
            "label": "Company Quality",
            "description": "Source quality classification for the company",
            "icon": "IconBuilding",
        },
    ],
    "person": [
        {
            "type": "NUMBER",
            "name": "sourceScore",
            "label": "Source Score",
            "description": "Original score supplied by the lead source",
            "icon": "IconGauge",
        },
        {
            "type": "TEXT",
            "name": "productInterest",
            "label": "Product Interest",
            "description": "Product or solution mentioned by the lead",
            "icon": "IconPackage",
        },
        {
            "type": "TEXT",
            "name": "leadSource",
            "label": "Lead Source",
            "description": "Origin and campaign source for the lead",
            "icon": "IconSourceCode",
        },
        {
            "type": "TEXT",
            "name": "sharedBy",
            "label": "Shared By",
            "description": "Person or process that supplied the lead",
            "icon": "IconUser",
        },
        {
            "type": "DATE_TIME",
            "name": "capturedAt",
            "label": "Captured At",
            "description": "Date and time when the lead was captured",
            "icon": "IconCalendar",
        },
    ],
}


def main() -> None:
    response = twenty_client._request("GET", "/rest/metadata/objects?limit=100")
    objects = {item["nameSingular"]: item for item in response.get("data", [])}
    report = {"created": [], "existing": []}

    for object_name, definitions in FIELD_DEFINITIONS.items():
        object_metadata = objects[object_name]
        existing = {field["name"] for field in object_metadata.get("fields", [])}

        for definition in definitions:
            qualified_name = f'{object_name}.{definition["name"]}'
            if definition["name"] in existing:
                report["existing"].append(qualified_name)
                continue

            payload = {
                "objectMetadataId": object_metadata["id"],
                "isNullable": True,
                "isUnique": False,
                **definition,
            }
            created = twenty_client._request(
                "POST",
                "/rest/metadata/fields",
                payload,
            )
            report["created"].append(
                {
                    "field": qualified_name,
                    "id": created.get("id"),
                    "type": created.get("type"),
                }
            )
            existing.add(definition["name"])

    verify = twenty_client._request("GET", "/rest/metadata/objects?limit=100")
    verify_objects = {
        item["nameSingular"]: item for item in verify.get("data", [])
    }
    report["verified"] = {
        object_name: sorted(
            field["name"]
            for field in verify_objects[object_name].get("fields", [])
            if field["name"] in {item["name"] for item in definitions}
        )
        for object_name, definitions in FIELD_DEFINITIONS.items()
    }

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
